name: marschpad
description: Marschpad - Dirigent + Musiker Apps
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4
  path_provider: ^2.0.14
  http: ^1.1.0
  web_socket_channel: ^3.0.3
  uuid: ^4.1.0
  syncfusion_flutter_pdfviewer: ^32.1.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0 

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" 
